{%- set params = [ 
  { "GAME": 1},
  { "GAME": 2},
  { "GAME": 3},
  { "GAME": 4},
  { "GAME": 5},
  { "GAME": 6},
  { "GAME": 7},
  { "GAME": 8}
]%}
{%- for p in params %}
{%- set GAME = p["GAME"] %}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sc-poc-2
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sc-poc-server
        image: jonghunbok/dummy-game:server
        command: ['python', '/app/simple-game-server.py']
        volumeMounts:
        - mountPath: '/tmp/games'
          name: sc-poc-pvc
        env:
        - name: GAME
          value: "{{ GAME }}"
      - name: sc-poc-client
        image: jonghunbok/dummy-game:client
        command: ['python', '/app/simple-game-client.py']
        volumeMounts:
        - mountPath: '/tmp/games'
          name: sc-poc-pvc
        env:
        - name: GAME
          value: "{{ GAME }}"
      volumes:
        - name: sc-poc-pvc
          persistentVolumeClaim:
            claimName: log-pv-claim
{%- endfor %}
