kubectl apply -f dual1.yml
kubectl apply -f dual2.yml
kubectl apply -f dual3.yml
kubectl apply -f dual4.yml
kubectl apply -f dual5.yml
kubectl apply -f dual6.yml
kubectl apply -f dual7.yml
kubectl apply -f dual8.yml
kubectl apply -f dual9.yml
kubectl apply -f dual10.yml
