---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  labels:
    app: sc-kube
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/sc-poc/
