---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
  labels:
    app: sc-kube
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
