---
apiVersion: batch/v1
kind: Job
metadata:
  name: sc-poc-0-serv
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sc-poc-server
        image: jonghunbok/dummy-game:server
        command: ['python', '/app/simple-game-server.py']
        volumeMounts:
        - mountPath: '/tmp/games'
          name: sc-poc-pvc
        env:
        - name: GAME
          value: "0"
      volumes:
        - name: sc-poc-pvc
          persistentVolumeClaim:
            claimName: log-pv-claim

